### ISSUE TITLE
ovpn 

### ISSUE THREAD

**Issue by testingnic** [tickbh/wmproxy#8]
Hello, can you improve the documentation a little, I am currently using this tunnel with openvpn on my client I have this configuration.

[proxy]
server="216.189.154.18:80"
bind_addr = "127.0.0.1:8090"

mode="client"

but it doesn't work, but if I do it from the console arguments it works.
 this way

./wmproxy.exe -b 127.0.0.1:8090 -S 216.189.154.18:80

From ovpn I use -b 127.0.0.1:8090 as a proxy and achieve a connection.

How can I add or change in TCP and UDP as well as in client and server

and add headers in client

I would like you to expand the document better.

I do -h but it doesn't explain much

**Comment by tickbh** [comment]
client toml config may name client.toml
```toml
control = "127.0.0.1:8838"
[proxy]
# 连接服务端地址
server = "127.0.0.1:8091"
bind_addr = "0.0.0.0:8090"
flag = "http https socks5"
# 连接服务端是否加密
ts = true
two_way_tls = true
mode = "client"
```

```bash
run ./wmproxy -c client.toml
```

server toml config may name server.toml
```toml
[proxy]
#绑定的ip地址
bind_addr = "127.0.0.1:8091"

# 双向认证
two_way_tls = true
#接收客户端是为是加密客户端
tc = true
#当前服务模式，server为服务端，client为客户端
mode = "server"
```

```bash
run ./wmproxy -c client.toml
```

### test 
```bash
export http_proxy="http://127.0.0.1:8090"
curl http://www.baidu.com
```

and then show
```
<!DOCTYPE html>
<!--STATUS OK--><html> <head><meta http-equiv=content-type content=text/html;charset=utf-8><meta http-equiv=X-UA-Compatible content=IE=Edge><meta content=always name=referrer><link rel=stylesheet type=text/css href=http://s1.bdstatic.com/r/www/cache/bdorz/baidu.min.css><title>百度一下，你就知道</title></head>...
```
